# This rule is not used by the project aws-role-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to aws.myorg.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aws-role-controller
    app.kubernetes.io/managed-by: kustomize
  name: awsroleassignment-viewer-role
rules:
- apiGroups:
  - aws.myorg.io
  resources:
  - awsroleassignments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.myorg.io
  resources:
  - awsroleassignments/status
  verbs:
  - get
