# This rule is not used by the project aws-role-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the aws.myorg.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aws-role-controller
    app.kubernetes.io/managed-by: kustomize
  name: awsroleassignment-editor-role
rules:
- apiGroups:
  - aws.myorg.io
  resources:
  - awsroleassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.myorg.io
  resources:
  - awsroleassignments/status
  verbs:
  - get
