apiVersion: aws.myorg.io/v1
kind: AWSRoleAssignment
metadata:
  labels:
    app.kubernetes.io/name: aws-role-controller
    app.kubernetes.io/managed-by: kustomize
  name: awsroleassignment-sample
spec:
  # TODO(user): Add fields here
